services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py load_initial_auth_db &&
            python manage.py runserver 0.0.0.0:8000"
    # python manage.py load_initial_waste_db &&
    # python manage.py start_periodic_tasks &&
    # python manage.py load_some_waste_transfer &&
    # uvicorn app.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  # redis:
  #   image: redis:7.0.11-alpine
  #   # ports:
  #   #   - 6379:6379
  #   depends_on:
  #     - broker
  #   volumes:
  #     - redis_data:/data

  broker:
    image: "rabbitmq:alpine"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # ports:
    #   - 5672:5672
    #   - 15672:15672

  flower:
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672/
    volumes:
      - flower_data:/data

  celery:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
      celery -A app worker -l INFO"
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
      - app

  celery_beat:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
      celery -A app beat -l INFO"
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

volumes:
  rabbitmq_data:
  postgres-data:
  redis_data:
  flower_data: