# Generated by Django 5.0.1 on 2024-06-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_videorecording_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtask',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='taskeyeblink',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
